// Major Pakistani banks, for the "Bank Account" withdrawal method dropdown.
const List<String> kPakistaniBanks = [
  'Habib Bank Limited (HBL)',
  'United Bank Limited (UBL)',
  'MCB Bank Limited',
  'Allied Bank Limited (ABL)',
  'Bank Alfalah',
  'Meezan Bank',
  'Faysal Bank',
  'National Bank of Pakistan (NBP)',
  'Bank Al Habib',
  'Askari Bank',
  'Standard Chartered Bank Pakistan',
  'Soneri Bank',
  'JS Bank',
  'Habib Metropolitan Bank',
  'Silk Bank',
  'Summit Bank',
  'The Bank of Punjab',
  'The Bank of Khyber',
  'Dubai Islamic Bank Pakistan',
  'Al Baraka Bank Pakistan',
  'Sindh Bank',
  'First Women Bank',
];
