// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWdCp6A4U7QbCB6jsRA4LF9lTBX32LPQo',
    appId: '1:690756156202:web:0d97b54e41924f2782bc53',
    messagingSenderId: '690756156202',
    projectId: 'notification-b086a',
    authDomain: 'notification-b086a.firebaseapp.com',
    storageBucket: 'notification-b086a.firebasestorage.app',
    measurementId: 'G-0KQ0WL5MEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC11FS3Wy6fIOHjPs2GsKZflAXCOiizw4w',
    appId: '1:690756156202:android:eab4cd8059c37c5182bc53',
    messagingSenderId: '690756156202',
    projectId: 'notification-b086a',
    storageBucket: 'notification-b086a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAydGu7ztPSRQdwr2TtYBF1eTunv9gtWnk',
    appId: '1:690756156202:ios:b3b4bf6393862f4382bc53',
    messagingSenderId: '690756156202',
    projectId: 'notification-b086a',
    storageBucket: 'notification-b086a.firebasestorage.app',
    iosBundleId: 'com.example.userSide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAydGu7ztPSRQdwr2TtYBF1eTunv9gtWnk',
    appId: '1:690756156202:ios:b3b4bf6393862f4382bc53',
    messagingSenderId: '690756156202',
    projectId: 'notification-b086a',
    storageBucket: 'notification-b086a.firebasestorage.app',
    iosBundleId: 'com.example.userSide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWdCp6A4U7QbCB6jsRA4LF9lTBX32LPQo',
    appId: '1:690756156202:web:e031b18d09c14e9182bc53',
    messagingSenderId: '690756156202',
    projectId: 'notification-b086a',
    authDomain: 'notification-b086a.firebaseapp.com',
    storageBucket: 'notification-b086a.firebasestorage.app',
    measurementId: 'G-YEHQMX5XF4',
  );
}
